name: TakeCommand
version: 1.0
main: me.Maxisy.TakeCommand.TakeCommandPlugin
commands:
  take:
    description: "Command that takes an item from player"
    usage: /take [item] [amount] [player]
    permission: take.take
    permission-message: "You don't have take.take permission!"
    default: op
  takecommand:
    description: "Reloads config.yml file"
    usage: /takecommand [reload]
    permission: take.reload
    permission-message: "You don't have take.reload permission!"
    default: op